### PR TITLE
Top bar with language switcher

### PR DESCRIPTION
**Pull request by htmlboy**
Language switcher displayed always on top, with a top bar with a darker color.

Solves #25

### CODE REVIEW

**Comment by andreslucena** [comment]
Deploy preview ready!

Built with commit e7b04e44c255a7f6223d478bb72f6e54eb6cfa70

https://deploy-preview-68--decidim-website.netlify.com

**Comment by xabier** [comment]
The Logo of Barcelona City Council overlaps with the lang-wrapper, is this intended?

image

**Comment by htmlboy** [comment]
@xavier it should be like this:
screen shot 2017-10-13 at 15 06 24

Can you force a reload and see if it's still happening?

**Comment by xabier** [comment]
I still see it as previous captures :(

It is not a big problem so I will merge and then we can work on it

BTW: my usarname is @xabier with B not V (just in case!)

**Comment by htmlboy** [comment]
@xabier Ooops sorry. Been in Catalonia for too long ^__^U

**Pull request merged**
