### PR TITLE
Content updates

### PR DESCRIPTION
**Pull request by htmlboy**
- Dynamic footer copyright and linked license
- Removed credits page
- Order change in home features
- Contact thank-you page for Netlify
- Random testimonials

### CODE REVIEW

**Comment by andreslucena** [comment]
Deploy preview for *decidim-website* ready!

Built with commit 1b517b487443101ff9500717e835d9ac96563e9f

https://deploy-preview-187--decidim-website.netlify.com

**Comment by htmlboy** [comment]
@andreslucena ready for review & merge!

**Comment by andreslucena** [comment]
Some feedback, sorry for the delay: 

* On catalan and spanish, on sending the form there's a problem with encoding 

photo5805591381329161775

* Also we should talk using "vosotros/vosaltres":  "Gràcies pel teu correu, et respondrem en breu."

Thanks

**Comment by htmlboy** [comment]
> Some feedback, sorry for the delay:
> 
>     * On catalan and spanish, on sending the form there's a problem with encoding
> 
> 
> photo5805591381329161775
> 
>     * Also we should talk using "vosotros/vosaltres":  "Gràcies pel teu correu, et respondrem en breu."
> 
> 
> Thanks

@andreslucena Weird… Browser & OS?

**Comment by andreslucena** [comment]
Firefox 66.0.1 - Linux Mint 19.1 Tessa

Seems like it's something on the flow, check it on https://deploy-preview-187--decidim-website.netlify.com
If you go directly to https://deploy-preview-187--decidim-website.netlify.com/es/thanks/ it's ok but if you fill the contact form you can see this error.

**Comment by htmlboy** [comment]
@andreslucena I've created a new Netlify deploy in my account: https://goofy-beaver-ecc4fc.netlify.com

I've also changed the form names and thanks pages names. So far, my deploy doesn't have the encoding problem, but yours still presents problems. I've noticed the thanks page in your Netlify deploy adds an additional script tag with the submission (mine doesn't), and it looks like its triggering the encoding issue. Is there any additional third-party service you've attached to the form? I've only created email notifications for all forms.

**Comment by andreslucena** [comment]
No other service here. It could be something related with the PR feature on netlify... I think it's better to merge to try it on prod. Is it all ready to make the merge?

**Comment by htmlboy** [comment]
@andreslucena Yes, I think so. Press the button if you're ready :-)

**Comment by andreslucena** [comment]
Merged and on production, the error is still there. 

I can't give you permissions to netlify until we add the badge: https://github.com/decidim/decidim.org/issues/189

**Pull request merged**
