### PR TITLE
New design with TailwindCSS

### LINKED ISSUE #281: Implement new design
- Prototip web: https://www.figma.com/proto/9KP8rBo6G1vLAqnve6PD2v/Decidim---Gr%C3%A0fica?page-id=0%3A1&node-id=420%3A61955&viewport=241%2C48%2C0.05&scaling=min-zoom&starting-point-node-id=420%3A61955&show-proto-sidebar=1
- Prototip mòbil (no està enllaçat, però podeu navegar-lo amb les fletxes del teclat): https://www.figma.com/proto/9KP8rBo6G1vLAqnve6PD2v/Decidim---Gr%C3%A0fica?page-id=250%3A18058&node-id=420%3A59373&viewport=241%2C48%2C0.11&scaling=min-zoom&starting-point-node-id=420%3A59373

- Disseny web (desktop): https://www.figma.com/file/9KP8rBo6G1vLAqnve6PD2v/?node-id=0%3A1
- Disseny web (mobile): https://www.figma.com/file/9KP8rBo6G1vLAqnve6PD2v/?node-id=250%3A18058

### PR DESCRIPTION
**Pull request by Crashillo**
Closes #281 

### Caveats
- Multiple non-english locales missing

### CODE REVIEW

**Comment by Crashillo** [comment]
Even though this PR is still in draft, @decidim/product you may go ahead and review the desktop site

**Comment by andreslucena** [comment]
@Crashillo it's looking good, let me know when we can check the mobile version too.

Some things that I've seen that need adjustments: 


-  [ ] 01 - Logos below the hero image: selection 

From the deploy preview: 
image

From the mockup:
image

It seems like it's using the logos from the partners data, it should be the used by  with a new attribute, using only these selected logos.

This should be changed in other sections, such as /get-started

image


- [ ] 02 - Logos below the hero image: color 

It should be gray instead of full color 

- [ ] 03 - "Already using decidim" homepage section logos sizes and colors

They should be a bit smaller and also with the red color

From the deploy preview: 

image

From the mockup:
image

- [ ] 04 - Missing sections in footer 

From the deploy preview: 
image

From the mockup:
image

- [ ] 05 - Missing links in FAQs

I found it in this question but it's probably in all: 


image

- [ ] 06 - Missing animation in /get-started/

image


- [ ] 07 - Language selector

Doesn't seems to work

image

- [ ] 08 - Accept privacy policy checkbox

(I know this wasn't in the mockup, sorry about that) 

Can we move the checbkox to the left of the "I accept.. "? 

image


---- 

This is more to @carolromero, but there seems to be lots of images, links and contents missing, can you check that please? 

Also to @carolromero - there's a block about the newsletter content in hte Press page, that isn't feasible for now, can we change that to blog posts or remove it? 

https://www.figma.com/proto/9KP8rBo6G1vLAqnve6PD2v/Decidim---Gr%C3%A0fica?page-id=0%3A1&node-id=110%3A14238&viewport=241%2C48%2C0.05&scaling=min-zoom&starting-point-node-id=420%3A61955 

The same with the Newsletter page, I think we should drop this from v1

https://www.figma.com/proto/9KP8rBo6G1vLAqnve6PD2v/Decidim---Gr%C3%A0fica?page-id=0%3A1&node-id=229%3A5612&viewport=241%2C48%2C0.05&scaling=min-zoom&starting-point-node-id=420%3A61955

**Comment by Crashillo** [comment]
> It seems like it's using the logos from the partners data, it should be the used by with a new attribute, using only these selected logos.

That's it. Both home and get-started widgets are currently displaying a random set of partners (every time changes). I'll append an extra attribute in https://github.com/decidim/decidim.org/blob/feat/281-new-design/data/partners.yml to filter which ones should be displayed, I'll provide further info then.

> It should be gray instead of full color

:thinking: Looks like a deployment bug. `grayscale` class is applied

> "Already using decidim" homepage section logos sizes and colors

In order to make that work, specially the blend color, it requires to edit every single logo, since the current images are not compatible. Besides, it's quite important that those logos won't be altered, or changed, in order to apply the color filters properly.

> Missing sections in footer

I've created a [data file](https://github.com/decidim/decidim.org/blob/feat/281-new-design/data/links.yml) to add/update/remove the links as you wish. Just let me know which are they, or simply, you may edit the file.

> Missing links in FAQs

Do you mean underlined links or clicking action (somewhere) goes to /faqs?

> Missing animation in /get-started/

Which animation should be? Endless slide to left/right? 

> Language selector

:thinking: Looks like another deployment bug

> Accept privacy policy checkbox

Do you mean in /contact site, right?

**Comment by andreslucena** [comment]
> > It seems like it's using the logos from the partners data, it should be the used by with a new attribute, using only these selected logos.
> 
> That's it. Both home and get-started widgets are currently displaying a random set of partners (every time changes). I'll append an extra attribute in [`feat`/281-new-design/data/partners.yml](https://github.com/decidim/decidim.org/blob/feat/281-new-design/data/partners.yml) to filter which ones should be displayed, I'll provide further info then.
> 

Sorry I meant the "installations" data (https://github.com/decidim/decidim.org/tree/feat/281-new-design/data/installations) 


> > It should be gray instead of full color
> 
> thinking Looks like a deployment bug. `grayscale` class is applied
> 

Oh I see. I've redeployed cleaning the cache but it's the same. Locally it's working so that's fine by me, let's check this when it's deployed to production. 

> > "Already using decidim" homepage section logos sizes and colors
> 
> In order to make that work, specially the blend color, it requires to edit every single logo, since the current images are not compatible. Besides, it's quite important that those logos won't be altered, or changed, in order to apply the color filters properly.
> 

Maybe we could do that with some script (I'm thinking on something like imagemagick/convert on CI or something like that). 

In which format do we need the images to be to do this client-side? 

> > Missing sections in footer
> 
> I've created a [data file](https://github.com/decidim/decidim.org/blob/feat/281-new-design/data/links.yml) to add/update/remove the links as you wish. Just let me know which are they, or simply, you may edit the file.

Ah ok, I'll make the suggestions there. 

> 
> > Missing links in FAQs
> 
> Do you mean underlined links or clicking action (somewhere) goes to /faqs?

I meant that we don't have the underline on links and that also clicking in an external link it isn't working. See how it works until now in https://decidim.org/faqs/ 

> 
> > Missing animation in /get-started/
> 
> Which animation should be? Endless slide to left/right?

There's a keynote with the animation (I can't see it in Ubuntu because it's on Keynote, a MacOS propietary format https://drive.google.com/file/d/16PiHB5YeAmzjglehZ9DjXsV_TKRbEMZQ/view) 
> 
> > Language selector
> 
> thinking Looks like another deployment bug

This one i can't see it locally 

> 
> > Accept privacy policy checkbox
> 
> Do you mean in /contact site, right?

I see that the image wasn't pasted... Yes, that's what I meant!

**Comment by Crashillo** [comment]
> Maybe we could do that with some script (I'm thinking on something like imagemagick/convert on CI or something like that).
In which format do we need the images to be to do this client-side?

It's not about the file format, but the color disposal. Look for instance:
image image 

They're different versions, the mockup has no background color however the current one has two: red and white. Other logos, like Helsinki, can easily be changed (because they're so simple), but those that contain several colors (Canton de Geneve, Assemblee Nationale...) cannot be modified in a straightforward way.

The problem with imagemagick or any script is about the complexity of deal with different logos/colors as you actually expected. Besides, this kind of design is only at the homepage, so you need to duplicate the logos (they're used at /partners), therefore, it's easier to tune them separately.

**Comment by andreslucena** [comment]
> It's not about the file format, but the color disposal. Look for instance:

Oh I didn't see catch that, thanks for the explanation!

@carolromero do you have a take on this issue regarding the logos' colors? 

Also, FYI @Crashillo, I've changed the base branch to merge to `feature/redesign` as we want to control when we do the deployment to production. It shouldn't make any difference on your side, as that branch was created from `main`.

**Comment by andreslucena** [comment]
>>> Missing animation in /get-started/

>> Which animation should be? Endless slide to left/right?

> There's a keynote with the animation (I can't see it in Ubuntu because it's on Keynote, a MacOS propietary format [drive.google.com/file/d/16PiHB5YeAmzjglehZ9DjXsV_TKRbEMZQ/view](https://drive.google.com/file/d/16PiHB5YeAmzjglehZ9DjXsV_TKRbEMZQ/view))

We've talked with the designer, and she has converted the animations, so they're visible: https://drive.google.com/drive/folders/1Xo2uWqc3xo8lhj3f_UT_jDOgI9E0Rjbu?usp=sharing

**Comment by carolromero** [comment]
@Crashillo can we have a look at how the logos would look in red? Thanks

**Comment by Crashillo** [comment]
> @Crashillo can we have a look at how the logos would look in red? Thanks

This is how they look like using a CSS filter, as you can see, results are unacceptable for some of them
Peek 2022-04-21 17-47

**Comment by Crashillo** [comment]
> Sorry I meant the "installations" data (https://github.com/decidim/decidim.org/tree/feat/281-new-design/data/installations)

I realized that was already implemented. They are selected using the `home: true` prop, and sorted using `priority: XX`. Because the current setting have 12 home logos, I filtered them to show only the first 6 ones. Is that behaviour ok?

**Comment by andreslucena** [comment]
> I realized that was already implemented. They are selected using the `home: true` prop, and sorted using `priority: XX`. Because the current setting have 12 home logos, I filtered them to show only the first 6 ones. Is that behaviour ok?

Yes, that's great, thanks!

**Comment by andreslucena** [comment]
I see that most of the things from my last comments are already solved, awesome! Great work @Crashillo

The only missing thing I see is just the red logo thing, I'll try to research a bit. As far as I understand, at the moment the only feasible solution would be to search for alternative logos, convert them locally and add an alternative version in the .yml, right? 

On the other hand, others minors things that I found: 

- [ ] 09 - Tab navigation broken in language selector


https://user-images.githubusercontent.com/717367/165284968-f385aaf9-295d-4865-bb86-f119322c030c.mp4


- [ ] 10 - Tab navigation broken in FAQs


https://user-images.githubusercontent.com/717367/165284982-de0558d2-4760-4e69-a4e9-55657ae4e91d.mp4


- [ ] 11 - Locale breaks on footer links

If you select any language other than English (for instance Spanish/es) and then you go to the footer, the links are for the English version (the prefix is missing).

**Comment by andreslucena** [comment]
Also the netlify deploy preview is broken, I just tried it locally with `bundle exec middleman build --verbose` and there are some exceptions related to `source/localizable/about.html.erb` and `source/localizable/get-started.html.erb` in some locales. Can you check that please? Thanks

**Comment by Crashillo** [comment]
> If you select any language other than English (for instance Spanish/es) and then you go to the footer, the links are for the English version (the prefix is missing).

What do you mean? Look at my localhost, the only odd thing I see is at the legal block, where translations are wrong for spanish
image

**Comment by Crashillo** [comment]
Deploys are restored

> I see that most of the things from my last comments are already solved, awesome! 

Yep, I was marking as solved in https://github.com/decidim/decidim.org/pull/283#issuecomment-1102301639

> The only missing thing I see is just the red logo thing, I'll try to research a bit. As far as I understand, at the moment the only feasible solution would be to search for alternative logos, convert them locally and add an alternative version in the .yml, right?

Since these logos are managed by third parties (more or less, they're dynamic, even though it's an admin who uploads the new ones) they should be treated as equals. That's is quite hard to achieve a common way to handle this, therefore you've to seek some tricks:
- This block is only a chunk of the all installations, so we can edit only those ones we wanna show, and make them static in the markup, that is, don't allow to display different ones.
- Don't apply such color filter, just show them as they are. In that way, you can still edit them through the .yml file (easier than html)

**Comment by andreslucena** [comment]
> What do you mean? Look at my localhost, the only odd thing I see is at the legal block, where translations are wrong for spanish

I mean the link destination

1. Go to https://deploy-preview-283--decidim-website.netlify.app/es/ 
2. Scroll to the footer
3. Click in "Funcionalidades"
4. See error: I went to https://deploy-preview-283--decidim-website.netlify.app/features/ 

I expected to go to https://deploy-preview-283--decidim-website.netlify.app/es/features/ (notice the missing /es/)

**Comment by andreslucena** [comment]
Related to the tab navigation, I see is the same for other parts of the web, like tabs (on /features and homepage). Just talked with  @carolromero, and we said that if you prefer we can first tackle the other design issues that we found, merge this to `feature/redesign` and after it's merged then you can fix that in subsequent PRs.

**Comment by Crashillo** [comment]
I did a refactor on the tabs UX, now they're "tabbable". Regarding the merge, I'm still working on the mobile version, I'm missing a few screens yet, may we hold til then?

**Comment by andreslucena** [comment]
Great news, we'll review it and let you know the things that we found: 

- [ ] tab navigation broken in "used by":
image

- [ ] tab navigation broken in "features":
image

>  09 - Tab navigation broken in language selector

I see that it goes automatically to every language. I think the current behavior should be like we currently have in Decidim: 

* It doesnt open automatically
* It opens with the enter key
* It closes with the escape key

https://user-images.githubusercontent.com/717367/165947314-8a5be80b-82ee-45f5-ae7a-8748f72eb6b2.mp4

**Comment by carolromero** [comment]
@Crashillo the design looks amazing!
Here are a couple of things I've seen in the review:
**Homepage**

- [ ] The desktop width is set to 1032px according to Foundation's breakpoints. Although we now use Tailwind, would it be an issue to set it to this width? 




- [ ] Missing dark background for top menu in homepage





- [ ] Missing language picker and copyright text in footer

- [ ] .text-defaults change to font-weight:300

- [ ] font size of blog posts doesn't match:





- [ ] disable hover for "pastilla" titles
https://www.awesomescreenshot.com/video/8710440?key=f88b35b7a1e1f3d720bd5aaca608f2cd

**Features page**

- [ ] Fix style intro text

**Comment by Crashillo** [comment]
> The desktop width is set to 1032px according to Foundation's breakpoints. Although we now use Tailwind, would it be an issue to set it to this width?

According tailwind, the current container's width uses the following marks:
Class | Breakpoint | Properties
-- | -- | --
container | None | width: 100%;
-| sm (640px) | max-width: 640px;
-| md (768px) | max-width: 768px;
-| lg (1024px) | max-width: 1024px;
-| xl (1280px) | max-width: 1280px;
-| 2xl (1536px) | max-width: 1536px;

You can change how much lateral space you set to each breakpoint, but the point is: do you want to set a maximum width of 1280px (w/o paddings you'd get ~1024px)? That will impact into larger monitors, which would display more blank space around the container

> Missing dark background for top menu in homepage

It's not missing, but the image is vertically centered. Larger your screen, less black background you'll see. I'll try to move it a bit based on the common breakpoints

> Missing language picker and copyright text in footer

They're behind the footer bar netlify places at the bottom. Click at the resize arrows to shrink such bar and you will see them.
image

>  .text-defaults change to font-weight:300

I do not understand this. The default font-weight is 400, both design and css class.


The rest of issues are crystal. I'll try to upload them asap.

**Comment by carolromero** [comment]
> You can change how much lateral space you set to each breakpoint, but the point is: do you want to set a maximum width of 1280px (w/o paddings you'd get ~1024px)? That will impact into larger monitors, which would display more blank space around the container

@Crashillo Good point about the large monitors. So let's use a larger container, but then we need to avoid having such long lines of text. In the design is calculated the maximum width as X columns of the grid. If we change the container we should specify a maximum width for the text elements, and this will solve it.
image

> I do not understand this. The default font-weight is 400, both design and css class.

That's correct, my bad.

**Comment by Crashillo** [comment]
> If we change the container we should specify a maximum width for the text elements, and this will solve it.

Ok, that's easy to handle it, simply setting a max-width to the paragraph elements. It's a common practice to use a width based on the character unit, `ch`, I provide you a couple of examples:

_No restriction_
image
_max-width: 80ch_
image
_max-width: 65ch_
image

All screenshots were taken in my screen 1920x1080. `80ch` is the common width in the text editors, and `65ch` is the width tailwind sets for their typography stuff. Which do you like the most?

**Comment by carolromero** [comment]
I'd go with the `65ch`. What do you think?

**Comment by Crashillo** [comment]
I set that up for paragraphs, take a look

**Comment by carolromero** [comment]
Looks good to me!

**Review by andreslucena — APPROVED** [review]
LGTM, thanks for the PR! We'd probably will catch some details in a few days but for the moment we'll approve it and merge it to `feature/redesign´ branch, so we can work on the contents. Thanks again! 🚀 🚀

**Pull request merged**
