### PR TITLE
Adding new section Features - #38

### PR DESCRIPTION
**Pull request by andreslucena**

### CODE REVIEW

**Comment by andreslucena** [comment]
Deploy preview ready!

Built with commit ae4ef3eec28ca9b88c2546e3bb184802aa818f0f

https://deploy-preview-46--decidim-website.netlify.com

**Comment by xabier** [comment]
@andreslucena please review this branche I made a number of new commits, I am not sure the links to the pdf files is working

**Comment by andreslucena** [comment]
Yes, they're not working. I'm gonna take a look. 

On the other hand I see it's missing the short summary text on Catalan and English.  Can you upload that?

**Comment by xabier** [comment]
I can't upload it right now.

but it is better to have to button without summary than having nothing
right now.

**Pull request merged**
