### PR TITLE
Documentation link points to docs.decidim.org

### PR DESCRIPTION
**Pull request by htmlboy**
Documentation link in navigation updated to point to docs.decidim.org

### CODE REVIEW

**Comment by htmlboy** [comment]
@andreslucena This PR can be merged now or once the new docs.decidim.org styles are published.

**Comment by andreslucena** [comment]
Deploy preview for *decidim-website* ready!

Built with commit f4631425fcaa887d87ab63578d4c99f11bfbc62f

https://deploy-preview-194--decidim-website.netlify.com

**Comment by andreslucena** [comment]
Ok, let's wait when we have the redesing on docs then.

**Comment by andreslucena** [comment]
I'll merge already so we don't have many PRs open at the same time.

**Comment by htmlboy** [comment]
@andreslucena 👍

**Pull request merged**
