### PR TITLE
Intro video in home

### PR DESCRIPTION
**Pull request by htmlboy**
Video in intro section. Solves #61

### CODE REVIEW

**Comment by andreslucena** [comment]
Deploy preview ready!

Built with commit 85ea3b768df9e70a52dc5cc76c22c6bea5dc7885

https://deploy-preview-92--decidim-website.netlify.com

**Comment by xabier** [comment]
@JuanLinaresLanzman please click here and let us know how you feel about this: https://deploy-preview-92--decidim-website.netlify.com

**Comment by JuanLinaresLanzman** [comment]
@xabier good. One doubt: when the video is finished, is it possible to turn it off and return to the home page?

**Comment by xabier** [comment]
@JuanLinaresLanzman I don't know but it is better merge this and work next. 

One serious problem that I witnessed with the video is that it takes about 10seconds to start, it has a very very slow beginning. We should work on this.

**Pull request merged**
