### PR TITLE
[WIP] change logo coditramuntana

### PR DESCRIPTION
**Pull request by isaacmg410**
Change logo version coditramuntana

### CODE REVIEW

**Comment by andreslucena** [comment]
Deploy preview ready!

Built with commit 14ba9909387a17ffc9effd304376287345f5f152

https://deploy-preview-94--decidim-website.netlify.com

**Comment by xabier** [comment]
@isaacmg410 are you sure? I liked more the previous logo! :smile:

**Comment by isaacmg410** [comment]
@xabier we sent it to our designer for review :)

**Comment by xabier** [comment]
so, do you want me to Merge or should I wait?

**Comment by isaacmg410** [comment]
@xabier please wait. The designer is reviewing it

**Comment by xabier** [comment]
:+1:

**Comment by andreslucena** [comment]
Any news regarding this issue?

**Comment by tramuntanal** [comment]
Hi @andreslucena thanks for giving light into this issue :D 

Just form here a rebranding process started at CodiTramuntana and we're in WIP. Can you please leave this issue open?

**Comment by andreslucena** [comment]
Closing this issue because it's stale and I'm cleaning up all the open PRs.

If you want, you can open again with the new logo.

**Comment by tramuntanal** [comment]
@isaacmg410 when you have a second, can you replace for the new logo please?

**Pull request closed without merging**
