### PR TITLE
Community page

### PR DESCRIPTION
**Pull request by martuishere**
Community page layout.

### CODE REVIEW

**Comment by martuishere** [comment]
@andreslucena Could you please fill the translation files for the Community page so we can merge this? Please let me know if you need any help.

**Comment by andreslucena** [comment]
Deploy preview for *decidim-website* ready!

Built with commit eb256aaffefcd98e8418dea738316e1e6dcfb0c0

https://deploy-preview-190--decidim-website.netlify.com

**Comment by andreslucena** [comment]
ok, @carolromero is working on it.

**Comment by andreslucena** [comment]
It's already reviewed and fixed. @martuishere can we merge?

**Comment by htmlboy** [comment]
@andreslucena In the community diagram, shouldn't we make a difference between pull requests and published code?

Screenshot 2019-04-25 at 12 57 53

**Comment by andreslucena** [comment]
@htmlboy it was a bug on the HTML (step6 was step5). It's already fixed, I also added a text.

**Comment by martuishere** [comment]
@andreslucena Perfect. You can merge this branch whenever you're ready!

**Pull request merged**
