### PR TITLE
Inaccuracy initiative description

### PR DESCRIPTION
**Pull request by paarals**
https://meta.decidim.org/processes/bug-report/f/210/proposals/12839#comment_20269

### CODE REVIEW

**Comment by andreslucena** [comment]
Deploy preview for *decidim-website* ready!

Built with commit 5b6706739c9e03844489f655e1beb420defe5dec

https://deploy-preview-137--decidim-website.netlify.com

**Comment by andreslucena** [comment]
@paarals thank you for your help. 

@xabier @carolromero could you please check this? I think it's correct, and it should be also reflected on spanish and english.

**Comment by xabier** [comment]
It is correct

**Comment by andreslucena** [comment]
I was making some clean-up of old PRs and saw that we still had this :sweat_smile: 
This is finally fixed at https://github.com/decidim/documentation/commit/5ee00b390e9395214fa20bdeb63455bd43143068 
Thanks @paarals for catching this up and reporting it.

**Pull request closed without merging**
