### PR TITLE
New section: Blog

### PR DESCRIPTION
**Pull request by andreslucena**
This adds a new section (Blog) to add news with i18n to decidim.org

### CODE REVIEW

**Comment by andreslucena** [comment]
Deploy preview processing.

Built with commit 366dac84677b2920c8e7940bbb0a4b5a5864ca3c

https://app.netlify.com/sites/decidim-website/deploys/59d21a9e0b79b707e68d5a4a

**Comment by andreslucena** [comment]
@htmlboy we've uploaded the initial contents with some posts that we had already. You can check that on the preview app: 
 
https://deploy-preview-35--decidim-website.netlify.com/blog/

As you can see there's some inconsistencies on titles. Maybe we should use h3 for the titles inside a post (ie "Noves funcionalitats i millores d’usabilitat")? 

image

**Comment by xabier** [comment]
@htmlboy @andreslucena podéis revisar los conflictos?

**Comment by andreslucena** [comment]
I've solved them. Merging this PR.

**Pull request merged**
